version: '2'
services:
  service-mainapp:
    container_name: ${APP_NAME}-main
    image: helloapp
    ports:
      - '${APP_PORT}:8012'
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://service-mongodb:27017/${DB_NAME}
  service-mongodb:
    extends:
      file: mongodb.yml
      service: service-mongodb


