version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    volumes:
      - type: bind
        source: ./elasticsearch/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    volumes:
      - type: bind
        source: ./kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    volumes:
      - type: bind
        source: ./filebeat/filebeat.docker.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - elk
    command: filebeat -e -strict.perms=false
    user: root
#
#  apache:
#    image: httpd:2.4
#    labels:
#      - co.elastic.logs/module=apache2
#      - co.elastic.logs/fileset.stdout=access
#      - co.elastic.logs/fileset.stderr=error
#      - co.elastic.metrics/module=apache
#      - co.elastic.metrics/metricsets=status
#      - co.elastic.metrics/hosts='elasticsearch:9200'
#    ports:
#      - "8080:80"
#    networks:
#      - elk
#
  service-mainapp:
    container_name: ${APP_NAME}-main
    image: ${APP_IMAGE}
    labels:
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.message_key=message
      - co.elastic.metrics/metricsets=status
      - co.elastic.metrics/hosts='elasticsearch:9200'
    ports:
      - '${APP_PORT}:8012'
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,swagger,elk
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://service-mongodb:27017/${DB_NAME}
  service-mongodb:
    extends:
      file: mongodb.yml
      service: service-mongodb

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
